name: Deploy Quiz API

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.1
        with:
          ssh-private-key: ${{ secrets.DEPLOY_SSH_KEY }}

      - name: Deploy to server
        run: |
          ssh -o StrictHostKeyChecking=no spectres@${{ secrets.DEPLOY_HOST }} << 'EOF'
            cd /home/spectres/quiz-api
            git pull origin main
            docker-compose down
            docker-compose build --no-cache
            docker-compose up -d
            # To do
          EOF